### ISSUE TITLE
No matching tag with version for nestpy v2.0.*

### ISSUE THREAD

**Issue by ramirezdiego** [NESTCollaboration/nestpy#103]
If one clones the v2.0.1 tag, the code still has the v2.0.0 version encoded, triggering incompatibilities and forcing people to default to master, instead of a stable release. See version line extracted from https://github.com/NESTCollaboration/nestpy/tree/v2.0.1:

https://github.com/NESTCollaboration/nestpy/blob/0be624fda16969d30f6097670258108376b8e957/setup.py#L126

**Comment by grischbieter** [comment]
The latest tagged release of version 2.0.2 should address this. Sorry for the versioning mismatch -- that was an error on my behalf from a year ago.

**Comment by ramirezdiego** [comment]
Thanks a lot!
