### ISSUE TITLE
Seg Faults when testing NESTCalc(VDetector*) constructor

### ISSUE THREAD

**Issue by infophysics** [NESTCollaboration/nestpy#11]
The following code crashes with a segmentation fault

##################################
from nestpy import nestpy
import unittest

class NESTcalcTestt(unittest.TestCase):
        def test_nestcalc_const_vdetect(self):
        detec2 = nestpy.VDetector()
        detec2.Initialization()
        nest2 = nestpy.NESTcalc(detec2)

if __name__ == "__main__":
        unittest.main()
##################################

The reason seems to be that the deconstructor in NEST.cpp for NESTcalc is also deleting the VDetector object, which causes a crash at the end of the function above.  Commenting that deletion out of NEST.cpp removes the error

**Comment by tunnell** [comment]
You seem to be able to specify not to delete the object using py::nodelete:

https://pybind11.readthedocs.io/en/stable/advanced/classes.html?highlight=destructor#non-public-destructors

Can you try that?  It causes a memory leak if you don't delete it yourself though.  However, the garbage collector should handle that.

**Comment by infophysics** [comment]
adjusted the pybind11 declaration for VDetector to 

py::class_<VDetector, std::unique_ptr<VDetector, py::nodelete>>(m, "VDetector")

which no longer causes a segmentation fault in unittest
