### ISSUE TITLE
Incomplete function for VDetector.FitTBA

### ISSUE THREAD

**Issue by infophysics** [NESTCollaboration/nestpy#12]
The current version of the VDetector class has the following function

  virtual std::vector<double> FitTBA(double xPos_mm, double yPos_mm,
                                     double zPos_mm) {
    std::vector<double> TopBotAsym;
    return TopBotAsym;
  }

which returns an empty vector.  When trying to run NESTcalc.xyResolution, line 1259 causes a Segmentation fault, as you would expect.

Vanilla NEST will not work unless FitTBA is specified for the particular Experiment (Detector)

**Comment by tunnell** [comment]
Can this be closed
