### ISSUE TITLE
Windows Installation

### ISSUE THREAD

**Issue by infophysics** [NESTCollaboration/nestpy#16]
A user on Windows 10 (64-bit) attempted to use pip install nestpy and got the following error;

Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\swkra\AppData\Local\Temp\pip-install-ah7sxnj3\nestpy\setup.py", line 69, in <module>
        history = open('HISTORY.md').read().replace('.. :changelog:', '')
    FileNotFoundError: [Errno 2] No such file or directory: 'HISTORY.md'

**Comment by tunnell** [comment]
Fixed.  Windows has to install from source so isn't supported at the moment because I don't know how to build the binaries.  Though this problem may be an issue for Linux people, so fixed that part.
