### ISSUE TITLE
Throw error is not enough NR nuisance parameters specified

### ISSUE THREAD

**Issue by JelleAalbers** [NESTCollaboration/nestpy#24]
I'm seeing strange behaviour in the current nestpy's NR (interaction 0) yields: the results are NaN or zero much of the time, in a non-deterministic way, with no clearly identifiable pattern. In contrast, the beta yields (interaction 8) look plausible and are deterministic.

Setup:
  * Nestpy 1.1.2 installed from pypi
  * EL7 (Linux-3.10.0-957.12.2.el7.x86_64-x86_64-with-redhat-7.4-Nitrogen)

Example code:

```python
from collections import Counter
import platform
import nestpy
import numpy as np

print(platform.platform())
print(nestpy.__version__)

n_trials = int(1e5)
py, ey = np.zeros(n_trials), np.zeros(n_trials)

for i in range(n_trials):
    nc = nestpy.NESTcalc(nestpy.VDetector())
    interaction = nestpy.INTERACTION_TYPE(0)  # NR
    E = 10.  # keV
    A = 131.293
    Z = 54.
    field = 82.   # V/cm
    density = 2.9  # g/cm^3
    
    y = nc.GetYields(
        interaction,
        E,
        density,
        field,
        A,
        Z,
        (1,1))

    py[i], ey[i] = y.PhotonYield, y.ElectronYield
    
count = lambda arr: Counter(['NaN' if np.isnan(x) else x for x in arr])

print(count(py), count(ey))
```
Gives e.g.:
```
Linux-3.10.0-957.12.2.el7.x86_64-x86_64-with-redhat-7.4-Nitrogen
1.1.2
Counter({0.0: 62499, 'NaN': 37501}) Counter({1176.4705882352941: 87499, 'NaN': 12501})
```
However, even these results are not deterministic. Here are a few more runs:
```
Linux-3.10.0-957.12.2.el7.x86_64-x86_64-with-redhat-7.4-Nitrogen
1.1.2
Counter({0.0: 37500, 'NaN': 37498, 10.011176959885258: 12501, 5.0055884799426291: 12501}) Counter({1176.4705882352941: 49999, 0.0: 25002, 'NaN': 24999})
```
```
Linux-3.10.0-957.12.2.el7.x86_64-x86_64-with-redhat-7.4-Nitrogen
1.1.2
Counter({'NaN': 37501, 0.0: 25000, 10.011176959885258: 25000, 1176.4705882352941: 12499}) Counter({1176.4705882352941: 37500, 0.0: 37499, 'NaN': 25001})
```
Note that 1176.47 can appear both in the photon yield and electron yield... This smells like some problem with memory addressing (though I haven't seen it segfault).

**Comment by tunnell** [comment]
Can you look at the example?  Specifically, the nuisance parameters where you have (1,1) now

**Comment by tunnell** [comment]
```
from collections import Counter
import platform
import nestpy
import numpy as np

print(platform.platform())
print(nestpy.__version__)

n_trials = int(1e5)
py, ey = np.zeros(n_trials), np.zeros(n_trials)

for i in range(n_trials):
    nc = nestpy.NESTcalc(nestpy.VDetector())
    interaction = nestpy.INTERACTION_TYPE(0)  # NR
    E = 10.  # keV
    A = 131.293
    Z = 54.
    field = 82.   # V/cm
    density = 2.9  # g/cm^3
    nuisance_parameters = [11., 1.1, 0.0480, -0.0533, 12.6,
                           0.3, 2., 0.3, 2., 0.5, 1.]
    
    y = nc.GetYields(
        interaction,
        E,
        density,
        field,
        A,
        Z,
        nuisance_parameters)

    py[i], ey[i] = y.PhotonYield, y.ElectronYield
    
count = lambda arr: Counter(['NaN' if np.isnan(x) else x for x in arr])

print(count(py), count(ey))
```

Counter({83.124055730761668: 100000}) Counter({55.437708463526754: 100000})

**Comment by tunnell** [comment]
I renamed this issue.  We should:

- Sensible default for nuisance parameters so don't need to specify
- Error if wrong number of arguments given.

I think the real issue is that NEST shouldn't be accepting lists like this for parameters... but that's another issue.

**Comment by tunnell** [comment]
Can you update to 1.1.3, then look again at README?  Now you shouldn't have to specify any values at all.  Actually, all variables have sensible defaults.  Therefore, just pick energy for example (xenon is default).

**Comment by tunnell** [comment]
@JelleAalbers bump?

**Comment by JelleAalbers** [comment]
Thanks for solving this! Your solution also enables keyword argument support (or perhaps this already worked earlier, I recall it did not at some point). So I can now just do e.g.
```
import nestpy

nc = nestpy.NESTcalc(nestpy.VDetector())

y = nc.GetYields(
    interaction=nestpy.INTERACTION_TYPE(0),  # NR
    energy=10.,  # keV
    drift_field=82.,  # V/cm
)

y.PhotonYield, y.ElectronYield
```
> (83.12405573076167, 55.437708463526754)

I wonder what these nuisance parameters mean.. but since they are now out of sight of the user, I guess it does not matter much.

**Comment by tunnell** [comment]
The nuisance parameters are new to give people hyper control over NR model.  I think the idea is that you can vary these in fits e.g. recombination fluctuations.  

Next release, I hope you can also do `interaction='nr'` with fuzzy matching or something.  The next NEST release in a month will check the arguments to avoid this.
