### ISSUE TITLE
nc.GetYields for NR low-energy input results in 0 Ly and Qy

### ISSUE THREAD

**Issue by sophiaandaloro** [NESTCollaboration/nestpy#26]
The following is a NESTpy report for a low-energy issue on NR charge and light yield values.
The code I used is given below, and the plots that I made to visualize the error are included. The issue seems to be dependent on the drift field, for default parameters on NESTcalc, seems to be ~0.21 keV there is an automatic 0 yield return.

[https://gist.github.com/sophiaandaloro/26fdf4b712d92c3d1bd1cb2288b8bf63](url)

key area: 
```
nc = nestpy.NESTcalc()
interaction = nestpy.INTERACTION_TYPE(0) # NR
Energy = 0.218 #keV 
field= 100 #V/cm
y = nc.GetYields(interaction, 
                         energy = Energy, 
                         drift_field=field)
```

Full Energy vs. Yields spectra:
![download-1](https://user-images.githubusercontent.com/39460606/63532340-140abb00-c4d0-11e9-9833-0e1162d19292.png)

Area of question: 
![download](https://user-images.githubusercontent.com/39460606/63532368-25ec5e00-c4d0-11e9-8bf8-270b0881c88c.png)

Thanks for your help!

**Comment by tunnell** [comment]
Well done issue.  This is apparently a feature according to @mszydagis.  This just stressed how we need to automate these plots on the NEST website.
