### ISSUE TITLE
S1/S2 generation

### ISSUE THREAD

**Issue by JelleAalbers** [NESTCollaboration/nestpy#37]
Hi nestpy developers, I tried to generate S1 and S2 signals, but hit two problems:
  * `NESTcalc.GetS2` is missing. In `bindings.cpp`, it is [commented out](https://github.com/NESTCollaboration/nestpy/blob/400f50baf4bd79285a6a42ecb911cc766923731c/src/nestpy/bindings.cpp#L173), with the remark: "Currently not working because of VDetector.FitTBA()".
  * `NESTcalc.GetS1` expects the wrong type for its event position arguments. The true and smeared position are the second and third argument, called `double truthPos[3]` and `double smearPos[3]` in NEST. In nestpy, if I try to pass a three-element tuple, list, or numpy array (float32 and float64), I get an error: 

```
TypeError: GetS1(): incompatible function arguments. The following argument types are supported:
    1. (self: nestpy.nestpy.NESTcalc, arg0: nestpy.nestpy.QuantaResult, arg1: float, arg2: float, arg3: float, arg4: float, arg5: nestpy.nestpy.INTERACTION_TYPE, arg6: int, arg7: float, arg8: float, arg9: int, arg10: bool, arg11: List[int], arg12: List[float]) -> List[float]

Invoked with: <nestpy.nestpy.NESTcalc object at 0x7f1d14eac1b0>, <nestpy.nestpy.QuantaResult object at 0x7f1d165a5050>, array([0., 0., 0.]), array([0., 0., 0.]), 1.2578003686818313, 1.2578003686818313, INTERACTION_TYPE.beta, 0, 80.0, 5.0, 0, False, [], []
```
However, `GetS1` is perfectly happy and returns sensible S1 values if I pass just `0.` or another scalar for the positions.

I'm running nestpy 1.3.0 installed from pip, on Ubuntu 20.04.1 LTS, python 3.7.4.

**Comment by tunnell** [comment]
@sophiaandaloro did we fix this in the end?

**Comment by tunnell** [comment]
@JelleAalbers (not that you care anymore) but I think the calling pattern for GetS1 is just set by the C++ side, but we might add a more Pythonic calling pattern at some point if there is interest...

Actions here:

- Add GetS1 and GetS2 tests
- Reenable in bindings.cpp
- Add variable names and types for kwargs v.s. just args, and add defaults
- Clarify what reasonable defaults are 👍  (also, what is a reasonable detector to have as default?)
- Get build to pass
- Add to Readme some examples

**Comment by sophiaandaloro** [comment]
https://github.com/NESTCollaboration/nestpy/pull/41 
Above PR takes care of implementing the following issues brought up by @tunnell 
  * Add GetS1 and GetS2 tests
  * Reenable in bindings.cpp
  * Get build to pass
