### ISSUE TITLE
Vectorizing Yield functions

### ISSUE THREAD

**Issue by WenzDaniel** [NESTCollaboration/nestpy#40]
Dear nestpy-Team thanks a lot for your work to port NEST to Python. 

I have a question regarding `GetYields` would it be possible to vectorize this function in its energy argument? Calling this function for many energy deposits is quite time consuming. Even if the function is vectorized by `@np.vectorize` it can become a bottleneck. Other means like calling the function within a numba for-loop cannot be applied either here. 

Thanks a lot.

**Comment by sophiaandaloro** [comment]
Hey Daniel! 
Thanks for adding this issue. You can now call nestpy.GetYieldsVectorized with a numpy array to do this. Check out the helpers.py file in src/nestpy to see more useful modules. 

(note I think you brought up pip install nestpy is currently not working on linux, this issue should be resolved soon, it's simply missing the requirements.txt file in the pypi release. Can go the git clone way in the meantime. Thanks!)

**Comment by sophiaandaloro** [comment]
Ah, I see the decorator also caused issues for you. There may be no workaround in the simple bindings methods we have going right now, but @grischbieter is going to be working on this starting next week once he returns from some on-site duties to help out in terms of making functions in python that are faster and more user-friendly. I'll point him to this issue as a general warning that our current @np.vectorize method of getting numpy-friendly yields is apparently too slow for some applications. Thanks!

**Comment by WenzDaniel** [comment]
Hi Sophia, thanks a lot. I will look into the new version. Maybe `np.vectorize` is fine since we currently have issues with other bottlenecks.

**Comment by sophiafarrell** [comment]
Closing this since we have had vectorized functions in nestpy for a while now. We can open up a different issue for optimization if that is a separate problem.
