### ISSUE TITLE
Error while installing nestpy

### ISSUE THREAD

**Issue by nikita-0209** [NESTCollaboration/nestpy#44]
`pip install nestpy` leads to

```
Collecting nestpy
  Using cached https://files.pythonhosted.org/packages/ed/82/d14b68959d7cc98838267601e8ff9bd9716be0d9d1f549754c1b13d4108f/nestpy-1.3.3.tar.gz
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

How can I resolve this error? It was working fine till a couple of days ago.

**Comment by tunnell** [comment]
I updated link on writing enough info in bug report.  Look forward to hearing from you

**Comment by nikita-0209** [comment]
Hi, I was trying to install nestpy by executing the command `pip install nestpy` on Google Colab and my Local PC (Ubuntu OS). I ran into the error mentioned above both times. Eventually, I tried v1.3.0 and that worked out. So, perhaps we can close this issue now.

**Comment by sophiaandaloro** [comment]
Thanks, Nikita and apologies for the delay. We are working to fix this in which we will include the code for the build to be made locally as a backup for linux users. When we release 1.4.1 this should be fixed. Keeping open until it is finished though

**Comment by sophiaandaloro** [comment]
Fixed and closing this issue. Thanks again!
