### ISSUE TITLE
Error in BinomFluct()

### ISSUE THREAD

**Issue by falcaso** [NESTCollaboration/nestpy#48]
I noticed an issue when running my python code, I kept receiving the same error: "TypeError: BinomFluct(): incompatible function arguments". The problem is in the "static" definition of this function, on NEST.hh, line 163.
@sophiaandaloro  suggested the solution could be removing the "static" or finding a better way to bind to this function more effectively.

https://github.com/NESTCollaboration/nestpy/blob/0e657b3344b27c0627a30dc49485d083db33581a/src/nestpy/NEST.hh#L163

**Comment by jpbrodsky** [comment]
Removing the static from this function does not seem appropriate to me. It would remove an occasionally-useful feature from the core NEST library (access to these fluctuations without a NESTcalc instance). Instead, I would suggest pursuing the suggesting to find to this function in a different way.

**Comment by sophiaandaloro** [comment]
@tunnell given what Jason said, do you have any input on binding to BinomFluct as a static ?

**Comment by sophiaandaloro** [comment]
This has now been fixed in nestpy v1.4.1 (at least, tests run smoothly.) Comment if I am wrong, otherwise will close.
