### ISSUE TITLE
More complete testing

### ISSUE THREAD

**Issue by tunnell** [NESTCollaboration/nestpy#6]
Worth writing tests for all the exposed functions (@infophysics already iterated through all functions for his NEST.py)

**Comment by infophysics** [comment]
Tested all NESTcalc() functions (except xyResolution which requires a specification of the FitTBA function in VDetector) and everything worked.

**Comment by tunnell** [comment]
can you put it in unittest (like other example) then make a pull request?  In that PR, be sure to mention this issue #6

**Comment by tunnell** [comment]
This is addressed in #13.  Eventually, we can use more reasonable parameters instead of random numbers.  However, this works for testing that the calls work.
