### ISSUE TITLE
TravisCI builds on Linux failing

### ISSUE THREAD

**Issue by sophiafarrell** [NESTCollaboration/nestpy#64]
See: https://travis-ci.org/github/NESTCollaboration/nestpy/jobs/773401061

Issue: the Docker quota is met. This could potentially be fixed by our migrating over to travis-ci.com, which we already pay for. 
I believe this means we need to update our twine details in the travis.yml file. 

Tagging @grischbieter and @tunnell for more feedback on this.

**Comment by tunnell** [comment]
How do we change to .com?

**Comment by sophiafarrell** [comment]
My only guess is that we need to change the TWINE info to route to .com. I think you did this recently (2019-2020).

**Comment by sophiafarrell** [comment]
Fixed via #86.
