### ISSUE TITLE
Negative Values for Reombination Probability/Variance

### ISSUE THREAD

**Issue by Bunnycakes62** [NESTCollaboration/nestpy#65]
Dear nestpy team,

I am computing negative variance/recombination values with energy events below 1keV. This issue is not occurring in the C++ version of nest.

Please investigate.

**Comment by grischbieter** [comment]
@Bunnycakes62 could you please give an example of usage where you're seeing this? Specifically, is this for ER, NR, or some other unique particle or generator?  As it's not happening in the C++ code (and shouldn't be possible in the C++ code based on my understanding of GetQuanta(...) in NEST.cpp ) this should then likely be due to either bindings or usage. 

Any specifics of the code/commands you're calling will help significantly in trying to figure this out.

**Comment by Bunnycakes62** [comment]
Relevant function definitions and code.

  ```
import nestpy
  import numpy as np
  import scipy.special as ss
  
  
  def RecombOmegaER(efield, elecFrac):
      ampl = 0.14 + (0.043 - 0.14) / (1. + np.power(efield / 1210., 1.25))
      if ampl < 0:
          ampl = 0
      wide = 0.205
      cntr = 0.5
      skew = -0.2
      mode = cntr + np.sqrt(2 / np.pi) * skew * wide / np.sqrt(1 + skew ** 2)
      norm = 1. / (np.exp(-0.5 * np.power(mode - cntr, 2.) / (wide * wide)) * (1. + ss.erf(skew * (mode - cntr) / (wide * np.sqrt(2.)))))
      omega = norm * ampl * np.exp(-0.5 * np.power(elecFrac - cntr, 2.) / (wide * wide)) * (1. + ss.erf(skew * (elecFrac - cntr) / (wide * np.sqrt(2.))))
      if omega < 0:
          omega = 0
  
      return omega
  
  nc = nestpy.NESTcalc(nestpy.VDetector())
  interaction = nestpy.INTERACTION_TYPE(8) # beta interaction
  
  E = [0.1, 0.2, 2, 5, 10] #keV
  field = [10, 20, 100, 200, 500] #v/cm
  var = []
  recombination = []
  identifier = []
  omega_val = []
  epsilon = 0
  for e in E:
      for f in field:
  
          identifier.append((e,f))
  
          y = nc.GetYields(interaction, e, drift_field=f)
          photon = y.PhotonYield
          electron = y.ElectronYield
          exciton = y.ExcitonRatio
          efield = y.ElectricField
          elecFrac = electron/(photon+electron+epsilon) # avoid division by zero
          if elecFrac > 1:
              elecFrac = 1
          if elecFrac <0:
              elecFrac = 0
  
          # print('The photon yield is:', y.PhotonYield)
          # print('With statistical fluctuations',nc.GetQuanta(y).recombProb)
          z = nc.GetQuanta(y)
          Ne = z.electrons
          Nex = z.excitons
          Ni = z.ions
          Nph = z.photons
  
          recombProb = 1-(exciton+1)*electron/(photon+electron+epsilon)
          recombination.append(recombProb)
  
          omega = RecombOmegaER(efield, elecFrac)
          omega_val.append(omega)
  
          print(recombProb)
          # Recombination Fluctuations
          variance = recombProb * (1. - recombProb) * Ni + omega * omega * Ni * Ni
          var.append(variance)
  
  
  print("Identifier ", identifier)
  print("Variance ", var)
  print("Recombination ", recombination)
  print("Omega ", omega_val)
  
  import pandas as pd
  energy, efieldval = list(zip(*identifier))
  list_of_tuples = list(zip(energy, efieldval, var, recombination, omega_val ))
  df = pd.DataFrame(list_of_tuples, columns=["Energy", "Efield", "Variance", "Recombination", "Omega"])
  df.to_csv("NEST_results.csv", index=False)
```

**Comment by grischbieter** [comment]
Ah okay, so this doesn't appear to be a nestpy issue. You're not using nestpy to calculate the recombination probability; the only thing you're using nestpy for appears to be the photon yield.  Instead, you've only hard-coded sections of the GetQuanta(...) into this script, and you're missing the series of validity tests and if-statements in the NEST.cpp code that we use. https://github.com/NESTCollaboration/nest/blob/master/src/NEST.cpp#L195

I recommend either editing NEST.cpp and NEST.hh in nestpy/src/nestpy/ to allow the quanta result to output "recombProb", "Variance", and "Omega", and using nc.GetQuanta(...) to calculate these from NEST directly, or to make sure you're using the validity checks in GetYields and GetQuanta if you insist on hard-coding things in your own script. These validity checks are to handle all of the fringe cases in NEST where our models are less bounded by data. 

I'll leave this issue open for the weekend, to see if anyone has additional comments, but as this isn't a nestpy issue, I'll close it down early in the upcoming week. 

@Bunnycakes62 feel free to reach to me via email if you have additional questions.

**Comment by sophiafarrell** [comment]
Hey @grischbieter thanks for taking this question! Yep, if you look at how we call it in NEST as Greg showed, we have "Validity-checks" in place that will set our floor and ceiling to 0, and 1, respectively. I hope we are understanding the question right! 

If you'd like more functionality to get some of the quanta results from nestpy, please open a separate issue and let us know that that is desired, and we can work to add it as an output on the development-side (or better yet.. if you want to try your hand at development, make such a suggested change to the source code and open a PR for review.)
